// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/helloworld/demo.proto

package demo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDemoRequest) Reset() {
	*x = CreateDemoRequest{}
	mi := &file_api_helloworld_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDemoRequest) ProtoMessage() {}

func (x *CreateDemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDemoRequest.ProtoReflect.Descriptor instead.
func (*CreateDemoRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_demo_proto_rawDescGZIP(), []int{0}
}

type CreateDemoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDemoReply) Reset() {
	*x = CreateDemoReply{}
	mi := &file_api_helloworld_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDemoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDemoReply) ProtoMessage() {}

func (x *CreateDemoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDemoReply.ProtoReflect.Descriptor instead.
func (*CreateDemoReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_demo_proto_rawDescGZIP(), []int{1}
}

var File_api_helloworld_demo_proto protoreflect.FileDescriptor

const file_api_helloworld_demo_proto_rawDesc = "" +
	"\n" +
	"\x19api/helloworld/demo.proto\x12\n" +
	"helloworld\"\x13\n" +
	"\x11CreateDemoRequest\"\x11\n" +
	"\x0fCreateDemoReply2P\n" +
	"\x04Demo\x12H\n" +
	"\n" +
	"CreateDemo\x12\x1d.helloworld.CreateDemoRequest\x1a\x1b.helloworld.CreateDemoReplyB-\n" +
	"\n" +
	"helloworldP\x01Z\x1dapi/helloworld/demo/demo;demob\x06proto3"

var (
	file_api_helloworld_demo_proto_rawDescOnce sync.Once
	file_api_helloworld_demo_proto_rawDescData []byte
)

func file_api_helloworld_demo_proto_rawDescGZIP() []byte {
	file_api_helloworld_demo_proto_rawDescOnce.Do(func() {
		file_api_helloworld_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_demo_proto_rawDesc), len(file_api_helloworld_demo_proto_rawDesc)))
	})
	return file_api_helloworld_demo_proto_rawDescData
}

var file_api_helloworld_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_helloworld_demo_proto_goTypes = []any{
	(*CreateDemoRequest)(nil), // 0: helloworld.CreateDemoRequest
	(*CreateDemoReply)(nil),   // 1: helloworld.CreateDemoReply
}
var file_api_helloworld_demo_proto_depIdxs = []int32{
	0, // 0: helloworld.Demo.CreateDemo:input_type -> helloworld.CreateDemoRequest
	1, // 1: helloworld.Demo.CreateDemo:output_type -> helloworld.CreateDemoReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_demo_proto_init() }
func file_api_helloworld_demo_proto_init() {
	if File_api_helloworld_demo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_demo_proto_rawDesc), len(file_api_helloworld_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_demo_proto_goTypes,
		DependencyIndexes: file_api_helloworld_demo_proto_depIdxs,
		MessageInfos:      file_api_helloworld_demo_proto_msgTypes,
	}.Build()
	File_api_helloworld_demo_proto = out.File
	file_api_helloworld_demo_proto_goTypes = nil
	file_api_helloworld_demo_proto_depIdxs = nil
}
